#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 30-bookstack
PROCESS_NAME="bookstack"

check_container_initialized
check_service_initialized init
liftoff

### Perform LDAP Sync to populate user table
if [ "$AUTHENTICATION_TYPE" = "LDAP" ] && var_true "${ENABLE_LDAP_SYNC_USER}" ; then
  date >/dev/null
  print_debug "LDAP Sync routines Initialized on $(date)"

### Wait for Next time to start Syncing
  current_time=$(date +"%s")
  today=$(date +"%Y%m%d")

  if [[ $LDAP_SYNC_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
  else
        target_time=$(date --date="${today} ${LDAP_SYNC_BEGIN}" +"%s")
    if [[ "$target_time" < "$current_time" ]]; then
        target_time=$(($target_time + 24*60*60))
    fi
    waittime=$(($target_time - $current_time))
  fi

  print_notice "Next Sync at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
  sleep $waittime

### Commence LDAP Sync
  while true; do
    now=$(date +"%Y%m%d-%H%M%S")
    now_time=$(date +"%H:%M:%S")
    now_date=$(date +"%Y-%m-%d")
    print_notice "Synchronizing LDAP"
    cd ${NGINX_WEBROOT}
    silent sudo -u ${NGINX_USER} php artisan bookstack:syncldap

    ### Go back to Sleep until next Backup time
    sleep $(($LDAP_SYNC_INTERVAL*60))
  done
else
  s6-svc -d /var/run/s6/services/30-bookstack
fi