services:
  bookstack-app:
    image: docker.io/nfrastack/bookstack
    container_name: bookstack-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack.rule=Host(`bookstack.example.com`)
      - traefik.http.services.bookstack.loadbalancer.server.port=80
    volumes:
      - ./data:/data
      - ./logs:/www/logs/
    environment:
      - CONTAINER_NAME=bookstack-app

      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_NAME=bookstack
      - DB_USER=bookstack
      - DB_PASS=bookstackpass

      - SITE_URL=https://bookstack.example.com
    networks:
      - proxy
      - services
    restart: always

  bookstack-db:
    image: docker.io/tiredofit/mariadb
    container_name: bookstack-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=bookstack
      - DB_USER=bookstack
      - DB_PASS=bookstackpass
    networks:
      - services
    restart: always

  bookstack-db-backup:
    image: docker.io/tiredofit/db-backup
    container_name: bookstack-db-backup
    links:
      - bookstack-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=bookstack-db-backup
      - DB01_HOST=bookstack-db
      - DB01_TYPE=mariadb
      - DB01_NAME=bookstack
      - DB01_USER=bookstack
      - DB01_PASS=bookstackpass
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
