# Manual Workflow (Application)

name: manual

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build'
        required: false
jobs:
#  php80:
#    uses: tiredofit/github_actions/.github/workflows/php80_alpine_amd64_armv7_arm64.yml@main
#    secrets: inherit
#  php81:
#    uses: tiredofit/github_actions/.github/workflows/php81_alpine_amd64_armv7_arm64.yml@main
#    secrets: inherit
  php83:
    uses: tiredofit/github_actions/.github/workflows/php83_alpine_amd64.yml@main
    secrets: inherit

